version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./image/postgres/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quadx
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080
  php:
    build: ./image/php/
    ports:
      - "9000:9000"
    volumes:
      - ./lumen/:/var/www/html
    links:
      - db
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
